channels: 
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - requests
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - pip:
    - tqdm
    - Flask
    - streamlit


